### ISSUE TITLE
APIs cannot be deleted

### ISSUE THREAD

**Issue by greg-k-taylor** [biothings/biothings_studio#31]
After an API has been created with the following steps it cannot be deleted with the trash can button in the web interface using studio4mychem_0.1e

Create an API.
1.  Dump/Upload a source (unii)
2.  Create a build and index it
3.  Create a new API
* name - test_api
* description - "My Test API"
* backend - test (localhost:9200) | unii
* port - 8000
* Ok
4.  Click the trash can button for 'test_api'

Result - the API 'test_api' is not deleted but should be.

**Comment by sirloon** [comment]
I can't reproduce this. This commit https://github.com/biothings/biothings.api/commit/85b5c9a4ec1c9ada5f114081c6b567d159c35c24#diff-c774faed9550607597011af8301bdeafR196 fixed issue with names including "-", also "_" is part of regex char \w so there must be something else. Can you post the logs when you click "delete" ?

**Comment by sirloon** [comment]
can't reproduce
