### ISSUE TITLE
Cannot create new builds with configuration containing dash (-) in its name.

### ISSUE THREAD

**Issue by CristianoYL** [biothings/biothings_studio#4]
# Issue description
When trying to create a new build, the process would fail if the configuration name contains a dash (`-`). The logs from the hub shows a 404:
```
WARNING:tornado.access:404 OPTIONS /build/my-test-config/new (172.17.0.1) 0.97ms
```

If we used underscore (`_`) instead, it would work.

# Steps to reproduce
- Go to Builds -> Menu -> New configuration.
- Enter a configuration name that contains dashes (e.g. **test-config**) and fill in other required fields as usual.
- After the configuration is created, select Menu -> test-config -> Create new build
- No build gets created after submission. (**ERROR HERE**)

**Comment by CristianoYL** [comment]
Additionally, if the build name contains dashes(-), the similar error would occur when we try to manipulate it (e.g: deleting a build). The build would not get deleted, and the log shows similar 404:
```
WARNING:tornado.access:404 OPTIONS /build/test-new-build (172.17.0.1) 0.66ms
```

**Comment by sirloon** [comment]
fixed in https://github.com/biothings/biothings.api/commit/85b5c9a4ec1c9ada5f114081c6b567d159c35c24
will be deployed in release 0.1e https://github.com/biothings/biothings_studio/milestone/1
