### ISSUE TITLE
Losing select a backend the API will connect to to serve the data

### ISSUE THREAD

**Issue by mlebeur** [biothings/biothings_studio#53]
Hi,

Thanks a lot for your wonderfull work.

I was using Biothings Studio to create a database on gene information.

But I enconter an issue because all the "backend the API will connect to to serve the data" has disaeppered from my list.

In the same time my already existing API does not respond anymore :

 curl localhost:8000/metadata
{}

So i tried to create a new buid from the same data, release and create the API but the problem stays.

My list of backend is and stays empty.

I don't know what to try next.

Have you got an idea on that issue.

Thanks a lot.

ManuEl LEBEURRIER

**Comment by newgene** [comment]
@mlebeur glad you found BioThings Studio is useful for your project. 

Based on your description, I cannot tell exactly what the problem is. Maybe a screenshot will help?

**Comment by mlebeur** [comment]
Thanks for you quick answer.

I fixed the issue. Some malformed data lead to an error leading to a lost connection to the backend.
